<a href="https://colab.research.google.com/github/Phimphika113/python_dataviz2023/blob/main/Pandas101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import pandas as pd

## Meta data = Data that describtion data

ใช้อธิบายช้อมูล

## CSV = Comma Separated Values
แต่ละค่าถูกคั่นด้วย comma
ลูกน้ำครบเท่ากันก่อนรันได้

.csv = Comma Separated Values

data.go.th

# นำ Data เข้า
- upload to colab  # กรณีใช้เเค่ครั้งเดียว
- link with google drive









































## upload to colab

In [ ]:
data0 = pd.read_csv('/ขุดลอกคลองย้อนหลัง.csv') # รันต่อครั้งถัดไปไม่ได้ มันจะหาย

In [ ]:
#data0

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data0.head() #ดูหัวตาราง

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

In [ ]:
data0.head(20) #ดูถึงตัว20

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
6,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,225400
7,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,452500
8,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,447000
9,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,497000
10,งบประจำปี,0,62,50210000,สำนักงานเขตภาษีเจริญ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50,189500
11,งบประจำปี,0,62,50260000,สำนักงานเขตจตุจักร,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทุ่งจากซอยวิภาวดีรังสิต 36 ถึงคลองลา...,426000
12,งบประจำปี,0,62,50320000,สำนักงานเขตราชเทวี,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองส้มป่อย จากบ่อสูบน้ำคลองส้มป่อยถึงคล...,561000
13,งบประจำปี,0,62,50350000,สำนักงานเขตบางพลัด,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองวัดดาวดึงษาราม,258000
14,งบประจำปี,0,62,50370000,สำนักงานเขตดินแดง,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกลำรางศรีศุภราช จากถนนสุทธิสารวินิจฉัยถึง...,437000
15,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างโรงเรียนคลองหนองใหญ่,210000
16,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างบริษัทประยูรวิศว์,486000
17,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...,454000
18,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างบ้านบางแค 2,410000
19,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองหลวงพ่อบ้านแหลม,442000

In [ ]:
data0.tail() #ดูท้ายตาราง

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [ ]:
data0.shape

(692, 9)

In [ ]:
data0.describe() # ใช้ตรวจสอบเบื้องต้นได้เลย
#ขึ้นเฉพาะตัวเลข

         Issue_No  Fiscal_year  Department_code  Approved_buget
count  692.000000   692.000000     6.920000e+02    6.920000e+02
mean     0.333815    64.543353     4.534202e+07    1.482811e+06
std      0.474972     1.476149     1.303279e+07    2.464625e+06
min      0.000000    62.000000     1.100000e+07    0.000000e+00
25%      0.000000    63.000000     5.013000e+07    4.100000e+05
50%      0.000000    65.000000     5.023000e+07    5.980000e+05
75%      1.000000    66.000000     5.036000e+07    1.628250e+06
max      2.000000    66.000000     5.050000e+07    2.850000e+07

## link with google drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')  # mount =  เชื่อมไดร์ฟ

Mounted at /content/drive

In [27]:
data1 = pd.read_csv('/content/drive/MyDrive/ปี 3/DataViZ23Data/ขุดลอกคลองย้อนหลัง.csv')
data1.head()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

In [ ]:
data1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [ ]:
data1.head(10)  # ดูหัวตาราง จากแถวบน 10 แถวแรก นับจาก 0-9

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
6,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,225400
7,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,452500
8,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,447000
9,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,497000

In [ ]:
data1.tail(10) # ดูท้ายตาราง จากข้างล่าง

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
42615,36172,unittype_34140,project_14663,2 Bedroom,2,Condo,คอนโด,NaN,60.0,3500000.0,...,1.0,NaN,NaN,NaN,NaN,NaN,2022-02-28 15:30:05,2022-02-28 14:43:35,baania,https://baania.com/th/project/พลัส-คอนโด-โคราช...
42616,28981,unittype_25373,project_10133,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,NaN,...,1.0,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:20:09,2020-10-14 00:49:06,baania,https://baania.com/th/project/ระยองการ์เด้นฮิล...
42617,35109,unittype_1459,project_711,บ้านแสงรุ่ง,3,Townhome,ทาวน์โฮม,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:46,2020-10-14 00:39:29,baania,https://baania.com/th/project/บ้านแสงรุ่ง-711/...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,130.0,36500000.0,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...
42620,37109,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,NaN,157.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,NaN,133.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [ ]:
data1.shape # ดูขนาด กี่เเถวกี่หลัก

(692, 9)

In [ ]:
data1.describe()

         Issue_No  Fiscal_year  Department_code  Approved_buget
count  692.000000   692.000000     6.920000e+02    6.920000e+02
mean     0.333815    64.543353     4.534202e+07    1.482811e+06
std      0.474972     1.476149     1.303279e+07    2.464625e+06
min      0.000000    62.000000     1.100000e+07    0.000000e+00
25%      0.000000    63.000000     5.013000e+07    4.100000e+05
50%      0.000000    65.000000     5.023000e+07    5.980000e+05
75%      1.000000    66.000000     5.036000e+07    1.628250e+06
max      2.000000    66.000000     5.050000e+07    2.850000e+07

NaN(เเนน)= Not a Number

DF = DataFrame เป็นชื่อ Data Structure ที่ Pandas ใช้

# ชี้ค่าในตาราง (indexing)
ชี้ค่าติดลบไม่ได้

## มุมมองตาราง df [columns][rows]

In [4]:
data1[['Budget_resource']]

    Budget_resource
0         งบประจำปี
1         งบประจำปี
2         งบประจำปี
3         งบประจำปี
4         งบประจำปี
..              ...
687     งบเพิ่มเติม
688     งบเพิ่มเติม
689     งบเพิ่มเติม
690     งบเพิ่มเติม
691     งบเพิ่มเติม

[692 rows x 1 columns]

In [ ]:
data1['Budget_resource'][690] # data[ชื่อคอลัมน์][แถว]

'งบเพิ่มเติม'

In [ ]:
data1.columns #ดู col. ทั้งหมด

Index(['Budget_resource', 'Issue_No', 'Fiscal_year', 'Department_code',
       'Department', 'Core_budget_code', 'Expenditure_category', 'Item_name',
       'Approved_buget'],
      dtype='object')

In [ ]:
data1[['Approved_buget','Item_name','Department']] # #ดูแค่ 3 col. เลือกได้ว่าจะเอาคอลัมน์ไหนขึ้นก่อนขึ้นหลังเองได้

,Approved_buget,Item_name,Department
0,1193000,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,สำนักการระบายน้ำ
1,1100000,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,สำนักการระบายน้ำ
2,3075000,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,สำนักการระบายน้ำ
3,6240000,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,สำนักการระบายน้ำ
4,2685000,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,สำนักการระบายน้ำ
...,...,...,...
687,3686000,ขุดลอกคลองผักกะเฉด,สำนักงานเขตคลองสามวา
688,2575000,ขุดลอกคลองบึงทรายกองดิน,สำนักงานเขตคลองสามวา
689,689000,ขุดลอกลำรางซาฟารี,สำนักงานเขตคลองสามวา
690,464000,ขุดลอกลำรางตาจันทร์,สำนักงานเขตคลองสามวา
691,7578000,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,สำนักงานเขตบางบอน

In [ ]:
data1[['Approved_buget','Item_name','Department']][6:11] # data1 [[col 1,col 2]] [จน.row] ดูแค่ 3 column และเลือกมาแค่ row  6 ถึง row 10 (หรือ index 6 -11)

,Approved_buget,Item_name,Department
6,225400,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,สำนักงานเขตมีนบุรี
7,452500,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,สำนักงานเขตมีนบุรี
8,447000,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,สำนักงานเขตหนองจอก
9,497000,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,สำนักงานเขตหนองจอก
10,189500,ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50,สำนักงานเขตภาษีเจริญ

## มุมมองเเบบ Array

In [ ]:
data1.iloc[0,0] # .iloc [row,col] มองเเบบ Array // ชี้เป็นแถว คอลัม ติดลบ สไลด์ได้

'งบประจำปี'

In [ ]:
data1.iloc[0,-6] # index  เเถวที่ 0 คอลลัมน์ที่ -6

11000000

## Table Slicing
ไม่ค่อยมีประสิทธิภาพ
ต้องทราบพิกัด

In [ ]:
data1.iloc[-20 :,7:10]

                                             Item_name  Approved_buget
672  ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...          472000
673  ขุดลอกลำกระโดงแยกคลองบางขี้แก้ง (หมู่บ้านเอเวอ...          492000
674                         ขุดลอกคลองแยกคลองตาเทียม 1          469000
675  ขุดลอกลำกระโดงระหว่างซอยเพชรเกษม 43 กับ ซอยเพช...          493000
676                          ขุดลอกคลองแยกคลองยายเพิ่ม          481000
677                    ขุดลอกลำกระโดงข้างหมู่บ้านวรนุช          492000
678                                    ขุดลอกคลองตาตี่          483000
679                        ขุดลอกลำกระโดงข้างเดอะมอลล์          462000
680                      ขุดลอกลำกระโดงข้างบ้านบางแค 2          499000
681                                   ขุดลอกลำรางตาเชย         3559000
682                              ขุดลอกลำรางไทยเอราวัณ         3494000
683                             ขุดลอกคลองหนึ่งตะวันตก         4330000
684                               ขุดลอกคลองสองตะวันตก         9832000
685                                   ขุดลอกคลองกีบหมู         2925000
686                                 ขุดลอกคลองลำกะโหลก         3875000
687                                 ขุดลอกคลองผักกะเฉด         3686000
688                            ขุดลอกคลองบึงทรายกองดิน         2575000
689                                  ขุดลอกลำรางซาฟารี          689000
690                                ขุดลอกลำรางตาจันทร์          464000
691          ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล         7578000

 ## table Query

---


 df [logics] โดยที่ logics จะต้องมี จน.สมาชิก = จน.เเถวของ df

**โจทย์** อยากได้รายการทั้งหมดที่ได้รับการอนุมัติงบเกิน1ล้านบาท df[logics] โดยที่ logics จะต้องมีจำนวนสมาชิกเท่ากับจำนวนเเถวของ df

In [6]:
small_df = data1.iloc[-5:,:] # สร้างตารางเล็กขึ้นใหม่อีกตาราง
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [7]:
small_df[[False,True,True,False,False]] # เลือกเฉพาะ row ที่ต้องการ ; T = เอา F = ไม่เอา

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000

## ปั้น list of logics จากตาราง pandas

In [8]:
small_df [['Approved_buget']]<1000000 # การสร้าง logics จากตาราง pandas

     Approved_buget
687           False
688           False
689            True
690            True
691           False

In [ ]:
small_df [small_df['Approved_buget']<1000000] # การใช้ logics

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

# Quiz 3
> อยากได้รายการที่ได้รับการอนุมัติงบมากกว่า 1ล้านบาท เเต่ไม่เกิน 2 ล้านบาท

In [ ]:
data1[(data1['Approved_buget']>1000000) & (data1['Approved_buget'] <=2000000) ]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
22,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง,1508000
25,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...,1975000
...,...,...,...,...,...,...,...,...,...
660,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองสะพานยาว,1756000
662,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองบางรักและคูน้ำซอยจรัญสนิทวงศ์ 89,1859000
665,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองวัดน้อยนางหงษ์,1187000
666,งบเพิ่มเติม,1,66,50360000,สำนักงานเขตจอมทอง,NaN,งบลงทุน,"ขุดลอกคลองลัดบางสะแก (1),(2) จากคลองบางค้อและค...",1581000
670,งบเพิ่มเติม,1,66,50360000,สำนักงานเขตจอมทอง,NaN,งบลงทุน,"ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร (3),...",1388000

In [11]:
data1[(data1['Approved_buget']>1000000) & (data1['Approved_buget'] <=2000000) ]['Approved_buget'].mean() # หาค่าเฉลี่ยงบมากกว่า 1ล้านบาท เเต่ไม่เกิน 2 ล้านบาท

1457110.606060606

## ~Quiz 4~ (ตัวอย่างรุ่นพี่)
1. ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ร้านบาท
2. พื้นที่ และ จำนวนห้องนอนของบ้านที่แพงที่สุด
3. จำนวนที่จอดรถและห้องน้ำของบ้านที่ถูกที่สุด
4. ชนิดของบ้านที่แพงที่สุด
5. บ้านชนิดไหนมีปริมาณมากที่สุด

In [ ]:
# 1. ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ร้านบาท
data1[(data1['price_min'] >=3000000) & (data1['price_min']<=5000000)].describe()
# Ans 3.928111e+06	 = 3.928111  ล้านบาท

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,8943.000000,8943.000000,1066.000000,8148.000000,8.943000e+03,418.000000,0.0,6917.000000,5602.000000,8749.000000,8604.000000,3290.00000,3239.000000,4791.000000,1963.000000,150.000000,1223.000000,161.000000
mean,21153.925976,1285.383987,46.709559,138.785306,3.922594e+06,2.653110,NaN,2.132716,1.877722,2.406904,2.736634,1.00152,1.005557,1.016489,1.028018,1.033333,1.038430,1.105590
std,12338.077057,4901.447720,18.555223,66.760066,5.847665e+05,1.128124,NaN,0.577204,0.497313,0.915960,0.986672,0.03896,0.074351,0.127361,0.171131,0.214153,0.200641,0.396902
min,2.000000,1.000000,2.000000,20.100000,3.000000e+06,1.000000,NaN,0.000000,1.000000,0.000000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,10042.500000,1.000000,30.000000,96.000000,3.450000e+06,2.000000,NaN,2.000000,2.000000,2.000000,2.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21864.000000,2.000000,50.000000,145.000000,3.880000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,32198.000000,3.000000,60.000000,178.000000,4.400000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,42617.000000,20000.000000,99.000000,896.000000,5.000000e+06,7.000000,NaN,4.000000,10.000000,9.000000,10.000000,2.00000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000

In [ ]:
price_mean = data1[(data1['price_min'] >=3000000) & (data1['price_min']<=5000000)]['price_min'].mean()

In [ ]:
print(f'ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ล้านบาท คือ {int(price_mean):,}')

ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ล้านบาท คือ 3,922,594

In [ ]:
#2.พื้นที่และจำนวนห้องนอนของบ้านที่แพงที่สุด
data1['price_min'].max()

580000000.0

In [ ]:
data1[data1['price_min']==580000000][['area_usable_min','count_room_bed']]

       area_usable_min  count_room_bed
33122           1182.0             3.0

In [ ]:
data1[data1['price_min']==data1['price_min'].max()][['area_usable_min','count_room_bed','price_min']]

       area_usable_min  count_room_bed    price_min
33122           1182.0             3.0  580000000.0

In [ ]:
data1[data1['price_min']==data1['price_min'].max()]

In [ ]:
#3.จำนวนที่จอดรถและห้องน้ำที่ถูกที่สุด
data1['price_min'].min()

100000.0

In [ ]:
data1[data1['price_min']==100000][['count_parking','count_room_bath']]

       count_parking  count_room_bath
8640             NaN              1.0
11019            NaN              1.0
17941            NaN              1.0
30364            NaN              1.0

In [ ]:
data1[data1['price_min']==data1['price_min'].min()][['propertytype_name_en','count_parking','count_room_bath','price_min']]

      propertytype_name_en  count_parking  count_room_bath  price_min
8640                 Condo            NaN              1.0   100000.0
11019                Condo            NaN              1.0   100000.0
17941                Condo            NaN              1.0   100000.0
30364                Condo            NaN              1.0   100000.0

In [ ]:
# 4. ชนิดของบ้านที่แพงที่สุด
data1.describe()
data1[data1['price_min'] == 580000000]
# Ans Condo

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
33122,8629,unittype_37324,project_16305,Penthouse,2,Condo,คอนโด,NaN,1182.0,580000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:31,2020-10-14 00:55:50,baania,https://baania.com/th/project/เดอะ-สุโขทัย-เรส...

In [ ]:
# 4. ชนิดของบ้านที่แพงที่สุด
data1['propertytype_name_en'][data1['price_min'] == 580000000]

33122    Condo
Name: propertytype_name_en, dtype: object

In [ ]:
data1[data1['price_min']==data1['price_min'].max()][['propertytype_name_en','price_min']]

      propertytype_name_en    price_min
33122                Condo  580000000.0

In [ ]:
#5. บ้านชนิดไหนมีปริมาณมากที่สุด
data1['propertytype_name_en'].describe()

count              42625
unique                11
top       Detached House
freq               17670
Name: propertytype_name_en, dtype: object

In [ ]:
eight_rows_covid = data_covid.iloc[:8,3:] # ตารางตัวอย่าง
eight_rows_covid

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1  หญิง  74.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2  หญิง  73.0  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4  หญิง  66.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6  หญิง  57.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
7  หญิง  73.0  ...            หัวหิน  คนต่างชาติเดินทางมาจากต่างประเทศ

[8 rows x 7 columns]

In [ ]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]
#2.   ใส่ list ที่ มีค่า logic ของ แต่ละ row โดยที่ ค่า True คือ เลือก ค่า False คือไม่เลืิอก

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2  หญิง  73.0  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 7 columns]

In [ ]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'
#สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [ ]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']
#เราเอา 2 บรรทัดบนมาบวกกัน

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1  หญิง  74.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4  หญิง  66.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6  หญิง  57.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[6 rows x 7 columns]

In [ ]:
eight_rows_covid['district_of_onset'] == 'เมือง'

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: district_of_onset, dtype: bool

# Missing Value
- NaN = Not a Number
- Null = Null
- NA = Not Available/Not Authorised
- None

## ตรวจสอบ Missing (```isnull()```)
.isnull() ใช้ตรวจสอบว่าเป็น NaN หรือไม่

In [ ]:
data1.isnull() # ตรวจว่าค่านั้นเป็นค่า missing มั้ย ถ้า T = เป็น F = ไม่เป็น

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
687,False,False,False,False,False,True,False,False,False
688,False,False,False,False,False,True,False,False,False
689,False,False,False,False,False,True,False,False,False
690,False,False,False,False,False,True,False,False,False
691,False,False,False,False,False,True,False,False,False

In [ ]:
data1.isnull().any() # .any()ใช้หาค่าว่าง โดยเอาค่าความจริงใน column มา OR กัน ว่าในคอลัมน์ไหนบ้างที่มีค่าว่าง และ ไม่มีค่าว่าง

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code         True
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1.isnull().any().any() #เอา .any() ข้างบนมา OR อีก
                                    # ใช้สรุปว่าใน df ทั้งหมดมีค่าว่างหรือเปล่า

True

In [ ]:
data1.isnull().all() # .all() = เอาค่าความจริงใน col มา & กัน

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code        False
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

##การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown(fillna)
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)(fillna)

##DropNA

In [28]:
data1.shape

(692, 9)

In [26]:
data1.dropna().shape #หายเกิน50%ก็ถือว่าไม่ควร (ลบแบบคนไม่มีความรู้)

(266, 9)

In [12]:
data1.dropna(subset=['Fiscal_year']).shape #การลบ missing แบบคนมีความรู้ เพราะ data หายไปแค่ 1%

(692, 9)

In [23]:
data1.dropna(subset=['Core_budget_code']).shape

(266, 9)

In [ ]:
data1.dropna(subset=['Core_budget_code']) # ลบNaN ใน Core_budget_code

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
261,งบประจำปี,0,64,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองนายผล,488000
262,งบประจำปี,0,64,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองบางด้วน,410000
263,งบประจำปี,0,64,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองเนตรนุสรณ์ จากคลองบางบอนถึงสุดเขตกรุ...,978000
264,งบประจำปี,0,64,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองควาย,498000
265,งบประจำปี,0,64,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองโคกกะวะดี,486000

In [ ]:
data1.isnull().any()

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code         True
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [15]:
data1_1 = data1.dropna (subset=['Core_budget_code'])

In [18]:
data1.dropna (subset=['Core_budget_code'],inplace = True)#  อัพเดทตารางเรื่อยๆ // Core_budget_codeไม่เป็น True แล้ว

## Fillna

In [29]:
set (data1['Core_budget_code']) # เลือกเฉพาะค่าที่ซ้ำ

{'-',
 '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต',
 nan}

In [30]:
data1.fillna('-',inplace=True) # เปลี่ยน nan เป็น -

In [31]:
set(data1['Core_budget_code'])

{'-',
 '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต'}

In [32]:
data1.isnull().any()

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code        False
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1['Department']

0          สำนักการระบายน้ำ
1          สำนักการระบายน้ำ
2          สำนักการระบายน้ำ
3          สำนักการระบายน้ำ
4          สำนักการระบายน้ำ
               ...
687    สำนักงานเขตคลองสามวา
688    สำนักงานเขตคลองสามวา
689    สำนักงานเขตคลองสามวา
690    สำนักงานเขตคลองสามวา
691       สำนักงานเขตบางบอน
Name: Department, Length: 692, dtype: object

# HW 3
1. รายการที่เเพงเเละถูกที่สุดคือรายการไหน
2. รายการขุดลอกคูคลองของ'สำนักงานเขตคลองสาน'และ'สำนักงานเขตคลองสามวา'
3. จากข้อ 2 เขตไหนใช้งบประมาณมากกว่ากัน
4. Core budget ไหนมีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด ใน
'12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต'

1. รายการที่เเพงเเละถูกที่สุดคือรายการไหน

In [ ]:
hw3_1 = data1[['Item_name','Approved_buget']]

In [ ]:
hw3_data1_1 = hw3_1 [(hw3_1 ['Approved_buget'] == hw3_1 ['Approved_buget'].max()) | (hw3_1 ['Approved_buget'] ==hw3_1 ['Approved_buget'].min())]
hw3_data1_1

                                             Item_name  Approved_buget
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

2. รายการขุดลอกคูคลองของ'สำนักงานเขตคลองสาน'และ'สำนักงานเขตคลองสามวา'

In [ ]:
data1[(data1['Department'] == 'สำนักงานเขตคลองสาน') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
57,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคูน้ำสารภี 1,513000
58,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองเพลง\n,2218000
59,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...,89000
122,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองธรรมชาติและคลองแยกคลองวัดทองธร...,500000
123,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองโรงปลา,90000
212,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงซอยอิสรภาพ 3,162000
213,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองหลังวัดพิชัยญาติและคลองวัดน้อยเก่า,209000
214,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองพระยาเกษม,487000
215,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองข้างโรงเรียนปทุมวิทยา,80000
252,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...,6236000
253,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...,5815000
271,งบประจำปี,0,65,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...,659000
400,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางวัดแป้นทอง จากคลองสี่ตะวันตก ถึงคลอ...,1246200
401,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางครูพัว จากคลองสองตะวันตก ถึงคลองหนึ...,542200
402,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางตาชม จากคลองลำควายตาย ถึงคลองบางชัน,452300
403,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองเจ๊ก จากคลองหนึ่งตะวันตก ถึงสุดเขตคล...,1204500
404,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองซอยเชื่อมคลองลำแบนกับคลองหนองระแหง จ...,453600
441,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองโรงหนัง จากคลองบางไส้ไก่ถึงแม่น้ำเจ้...,1325000
442,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองข้างโรงน้ำแข็ง จากสุดระยะคลองถึงแม่น...,358000
443,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองข้างวัดอนงค์ จากคลองหลัง\nวัดพิชัยญา...,205000
681,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางตาเชย,3559000
682,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางไทยเอราวัณ,3494000
683,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองหนึ่งตะวันตก,4330000
684,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสองตะวันตก,9832000
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

3. จากข้อ 2. เขตไหนใช้งบเยอะกว่ากัน

In [ ]:
compare = data1[(data1['Department'] == 'สำนักงานเขตคลองสาม') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

In [ ]:
compare = data1.groupby('Department')['Approved_buget'].aggregate(['sum']) #.aggregate คือ
result1_3 =compare.groupby('Department')['sum'].aggregate(['max'])
result1_3.rename(columns ={'max':'งบประมาณรวมที่มากที่สุด'} )[0:3][1:3]

                      งบประมาณรวมที่มากที่สุด
Department
สำนักงานเขตคลองสาน                    6895000
สำนักงานเขตคลองสามวา                 51378800

4. Core budget ไหน ('12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม', '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร', '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

In [ ]:
hw3_data1_4= data1.groupby('Core_budget_code')['Approved_buget'].aggregate(['mean'])
result_1_4 =hw3_data1_4.groupby('Core_budget_code')['mean'].aggregate(['max'])
result_1_4['max'].max()
hw3_14 = result_1_4[(result_1_4['max'] == 1837500)]
hw3_14.rename(columns = {'max':'ค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด'})

                                                    ค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด
Core_budget_code
17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพั...                                1837500.0



---



---



---

### 1. เพื่อให้ได้ผลลัพธ์การจัดการ ```dropna()``` ต้องเอาตัวแปรมารับ

In [ ]:
this_data_nonull = this_data.dropna(subset=['sex','age'])

In [ ]:
this_data_nonull.isnull().any()

sex                  False
age                  False
province_of_onset     True
dtype: bool

### 2. update ตารางด้วยตัวแปร ```inplace```

In [ ]:
this_data.dropna(subset=['sex','age'],inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
this_data.isnull().any()

sex                  False
age                  False
province_of_onset     True
dtype: bool

In [ ]:
aa = this_data.dropna(subset=['sex','age'],inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
aa

### แทน missing ด้วยค่าที่เหมาะสม (```fillna()```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[12653 rows x 3 columns]

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 12653
จำนวน record หลัง drop missing ใน province 10662

#### 1. แทนด้วย class ใหม่

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-99, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
this_data_updated.tail(15)

          sex   age province_of_onset
12638  ไม่รู้ -99.0         สมุทรสาคร
12639  ไม่รู้ -99.0         สมุทรสาคร
12640     ชาย  66.0   พระนครศรีอยุธยา
12641     ชาย  29.0          ปทุมธานี
12642    หญิง  50.0           ราชบุรี
12643     ชาย  39.0              สตูล
12644    หญิง  49.0       สมุทรปราการ
12645    หญิง  44.0            ชลบุรี
12646     ชาย  18.0       สมุทรปราการ
12647     ชาย  42.0     กรุงเทพมหานคร
12648    หญิง  44.0            ชลบุรี
12649    หญิง  52.0             ระยอง
12650    หญิง  23.0             ระยอง
12651    หญิง  29.0             ระยอง
12652    หญิง  22.0               ตาก

In [ ]:
this_data_updated.isnull().any()

sex                  False
age                  False
province_of_onset    False
dtype: bool

#### 2. แทนด้วยค่าที่เหมาะสม


*   ตามใจคนทำ
*   ค่ากลาง

###### ตามใจคนทำ

In [ ]:
data_covid.head()

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [ ]:
data_covid_fillasiwant = data_covid.fillna(value={'sex':'หญิง'})  #เรามีข้อมูลว่า เพศหญิงมีเยอะกว่าเพศชาย

In [ ]:
data_covid_fillasiwant.isnull().any()

No.                      False
announce_date            False
notification_date         True
sex                      False
age                       True
nationality               True
province_of_isolation     True
province_of_onset         True
district_of_onset         True
risk                      True
dtype: bool

###### แทนด้วยค่ากลาง

In [ ]:
data_covid['age']

0        61.0
1        74.0
2        73.0
3        68.0
4        66.0
         ...
12648    44.0
12649    52.0
12650    23.0
12651    29.0
12652    22.0
Name: age, Length: 12653, dtype: float64

In [ ]:
data_covid['age'].mean()

38.054748339151

In [ ]:
data_covid_fillwithmean = data_covid.fillna(value={'age':data_covid['age'].mean()})

In [ ]:
data_covid_fillwithmean.isnull().any()

No.                      False
announce_date            False
notification_date         True
sex                       True
age                      False
nationality               True
province_of_isolation     True
province_of_onset         True
district_of_onset         True
risk                      True
dtype: bool



---



---



---

# การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
for row_i in range(len(data1)):
    print (data1.iloc[row_i,-2:] )
    print('------------------------')
    ### วนรูปในตารางเเบบง่ายๆ

Item_name         ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ
Approved_buget                                        1193000
Name: 0, dtype: object
------------------------
Item_name         ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...
Approved_buget                                              1100000
Name: 1, dtype: object
------------------------
Item_name         ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข
Approved_buget                                      3075000
Name: 2, dtype: object
------------------------
Item_name         ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...
Approved_buget                                              6240000
Name: 3, dtype: object
------------------------
Item_name         ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...
Approved_buget                                              2685000
Name: 4, dtype: object
------------------------
Item_name         ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...
Approved_buget                                              1207000
Name: 5, dtype: object
------------------------
Item_name         ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...
Approved_buget                                               225400
Name: 6, dtype: object
------------------------
Item_name         ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...
Approved_buget                                               452500
Name: 7, dtype: object
------------------------
Item_name         ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...
Approved_buget                                               447000
Name: 8, dtype: object
------------------------
Item_name         ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...
Approved_buget                                               497000
Name: 9, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50
Approved_buget                                 189500
Name: 10, dtype: object
------------------------
Item_name         ขุดลอกคลองทุ่งจากซอยวิภาวดีรังสิต 36 ถึงคลองลา...
Approved_buget                                               426000
Name: 11, dtype: object
------------------------
Item_name         ขุดลอกคลองส้มป่อย จากบ่อสูบน้ำคลองส้มป่อยถึงคล...
Approved_buget                                               561000
Name: 12, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดดาวดึงษาราม
Approved_buget                      258000
Name: 13, dtype: object
------------------------
Item_name         ขุดลอกลำรางศรีศุภราช จากถนนสุทธิสารวินิจฉัยถึง...
Approved_buget                                               437000
Name: 14, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงข้างโรงเรียนคลองหนองใหญ่
Approved_buget                                    210000
Name: 15, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงข้างบริษัทประยูรวิศว์
Approved_buget                                 486000
Name: 16, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...
Approved_buget                                               454000
Name: 17, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงข้างบ้านบางแค 2
Approved_buget                           410000
Name: 18, dtype: object
------------------------
Item_name         ขุดลอกคลองหลวงพ่อบ้านแหลม
Approved_buget                       442000
Name: 19, dtype: object
------------------------
Item_name         ขุดลอกคลองผู้ใหญ่เส็ง 1
Approved_buget                     347000
Name: 20, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงข้างห้างเดอะมอลล์บางแค
Approved_buget                                  482000
Name: 21, dtype: object
------------------------
Item_name         ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง
Approved_buget                                          1508000
Name: 22, dtype: object
------------------------
Item_name         ขุดลอกคลองบางแคจากถนนกาญจนาภิเษกถึงคลองพระยารา...
Approved_buget                                              4370000
Name: 23, dtype: object
------------------------
Item_name         ขุดลอกคลองบางมดจากคลองสนามชัยถึงคลองสวน
Approved_buget                                    6570000
Name: 24, dtype: object
------------------------
Item_name         ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...
Approved_buget                                              1975000
Name: 25, dtype: object
------------------------
Item_name         ขุดลอกคลองแจงร้อนจากแม่น้ำเจ้าพระยาถึงคลองขวาง
Approved_buget                                           2580000
Name: 26, dtype: object
------------------------
Item_name         ขุดลอกคลองลำไทรจากคลองลำปลาทิวถึงคลองลำตาจีน แ...
Approved_buget                                              1850000
Name: 27, dtype: object
------------------------
Item_name         ขุดลอกคลองหกโรงจากคลองหนึ่งถึงคลองสอง แขวงกระท...
Approved_buget                                              1825000
Name: 28, dtype: object
------------------------
Item_name         ขุดลอกคลองตาปลั่ง 1 จากคลองภาษีเจริญถึงคลองหนา...
Approved_buget                                              4380000
Name: 29, dtype: object
------------------------
Item_name         ขุดลอกคลองตาปลั่ง 2 จากถนนบางบอน 5 ถึงสุดระยะท...
Approved_buget                                              1626000
Name: 30, dtype: object
------------------------
Item_name         ขุดลอกลำรางสาธารณะเลียบหมู่บ้านบัณฑิตโฮมตั้งแต...
Approved_buget                                              1256000
Name: 31, dtype: object
------------------------
Item_name         ขุดลอกลำรางข้างบริษัทไทยเทยิ่น ตั้งแต่ถนนวิภาว...
Approved_buget                                              1117000
Name: 32, dtype: object
------------------------
Item_name         ขุดลอกคลองจรเข้ขบจากคลองประเวศบุรีรมย์\nถึงคลอ...
Approved_buget                                               855000
Name: 33, dtype: object
------------------------
Item_name         ขุดลอกคลองซอยจากคลองมหาสวัสดิ์ \nถึงคลองบางพรม
Approved_buget                                           1801000
Name: 34, dtype: object
------------------------
Item_name         ขุดลอกคลองเสาหินจากถนนพระราม 3   \nถึงสุดระยะท...
Approved_buget                                              2031000
Name: 35, dtype: object
------------------------
Item_name         ขุดลอกคลองวังเดิมจากคลองมอญ \nถึงคลองบางกอกใหญ่
Approved_buget                                            1641000
Name: 36, dtype: object
------------------------
Item_name         ขุดลอกคลองตาหนังจากคลองลำเจียก\nถึงคลองแสนแสบ
Approved_buget                                          4600000
Name: 37, dtype: object
------------------------
Item_name         ขุดลอกคลองบางคูเวียงจากคลองขุนศรีบุรีรักษ์\nถึ...
Approved_buget                                              1763000
Name: 38, dtype: object
------------------------
Item_name         ขุดลอกคลองปักหลักจากคลองจรเข้ขบ\nถึงคลองอาจารย์พร
Approved_buget                                               784000
Name: 39, dtype: object
------------------------
Item_name         ขุดลอกคลองมอญจากแม่น้ำเจ้าพระยา\nถึงคลองบางกอก...
Approved_buget                                              2475000
Name: 40, dtype: object
------------------------
Item_name         ขุดลอกคลองสามเสนจากคลองแยกเข้าบึงมักกะสัน\nถึง...
Approved_buget                                              8783000
Name: 41, dtype: object
------------------------
Item_name         ขุดลอกคลองบางโคลัดจากคลองวัดสิงห์\nถึงคลองรางข...
Approved_buget                                              4956000
Name: 42, dtype: object
------------------------
Item_name         ขุดลอกบึงเอกมัย
Approved_buget             280000
Name: 43, dtype: object
------------------------
Item_name         ขุดลอกคลองเจ้าคุณสิงห์จากบริเวณ\nซอยลาดพร้าว 8...
Approved_buget                                              2450000
Name: 44, dtype: object
------------------------
Item_name         ขุดลอกคลองขุนศรีบุรีรักษ์จากคลองมหาสวัสดิ์ \nถ...
Approved_buget                                              1866000
Name: 45, dtype: object
------------------------
Item_name         ขุดลอกบึงแอนเน็กซ์และคูระบายน้ำ\nซอยแอนเน็กซ์
Approved_buget                                          1600000
Name: 46, dtype: object
------------------------
Item_name         ขุดลอกคลองลำเจียรดับจากคลองแสนแสบ\nถึงคลองลำต้...
Approved_buget                                              2080000
Name: 47, dtype: object
------------------------
Item_name         ขุดลอกคลองบุปผารามจากคลองบางกอกใหญ่\nถึงคลองสม...
Approved_buget                                              1481000
Name: 48, dtype: object
------------------------
Item_name         ขุดลอกคลองสะพานสูง จากคลองบ้านม้าถึงคลองบ้านม้า
Approved_buget                                            1490000
Name: 49, dtype: object
------------------------
Item_name         ขุดลอกลำรางสุเหร่าหัวหมากน้อย จากคลองหัวหมากถึ...
Approved_buget                                              6650000
Name: 50, dtype: object
------------------------
Item_name         ขุดลอกคลองลำสาลี จากคลองหัวหมาก\nถึงคลองบ้านม้า
Approved_buget                                            6530000
Name: 51, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดศรีบุญเรือง จากคลองแสนแสบ\nถึงคลอ...
Approved_buget                                              2090000
Name: 52, dtype: object
------------------------
Item_name         ขุดลอกลำรางเชื่อมคลองบ้านม้า 1-2 \nจากคลองหัวห...
Approved_buget                                              2370000
Name: 53, dtype: object
------------------------
Item_name         ขุดลอกลำรางทะลาย (ลำรางแยกคลองหกขุด)\nจากคลองห...
Approved_buget                                               666000
Name: 54, dtype: object
------------------------
Item_name         ขุดลอกคลองหนองกง จากคลองลำบุรี \nถึงคลองบึงพระ...
Approved_buget                                              2184000
Name: 55, dtype: object
------------------------
Item_name         ขุดลอกคลองรางอ้อ-รางแก้ว\nจากถนนพหลโยธินถึงซอย...
Approved_buget                                              2130000
Name: 56, dtype: object
------------------------
Item_name         ขุดลอกคูน้ำสารภี 1
Approved_buget                513000
Name: 57, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดทองเพลง\n
Approved_buget                    2218000
Name: 58, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...
Approved_buget                                                89000
Name: 59, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดดีดวด
Approved_buget               1530000
Name: 60, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดประดู่
Approved_buget                 614000
Name: 61, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงซอยศักดิ์เจริญ\nจากคลองบางกอกใหญ...
Approved_buget                                               475000
Name: 62, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงหลังภัตตาคารแวร์ซายน์\nจากคลองบา...
Approved_buget                                               434000
Name: 63, dtype: object
------------------------
Item_name         ขุดลอกคลองซอยกิตติกมล  \nจากคลองบางกอกใหญ่ถึงบ...
Approved_buget                                               400000
Name: 64, dtype: object
------------------------
Item_name         ขุดลอกคลองต้นตาล (เกษจำเริญ)
Approved_buget                            380000
Name: 65, dtype: object
------------------------
Item_name         ขุดลอกคลองบ้านขมิ้น จากถนนสุทธาวาสถึงถนน \nวัง...
Approved_buget                                               493000
Name: 66, dtype: object
------------------------
Item_name         ขุดลอกคลองครูเสงี่ยม จากคลองบางแวกถึงหลังหมู่บ...
Approved_buget                                               264700
Name: 67, dtype: object
------------------------
Item_name         ขุดลอกคลองแยกคลองบางกอกใหญ่
Approved_buget                         464800
Name: 68, dtype: object
------------------------
Item_name         ขุดลอกคลองขวางตะวันออก จากคลองบางแวกถึงคลองบาง...
Approved_buget                                               410200
Name: 69, dtype: object
------------------------
Item_name         ขุดลอกคลองขวางตะวันตก จากคลองบางแวกถึงคลองบางเ...
Approved_buget                                               379400
Name: 70, dtype: object
------------------------
Item_name         ขุดลอกคลองครูสม จากคลองภาษีเจริญถึงคลองบางประทุน
Approved_buget                                              253800
Name: 71, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดอัปสรสวรรค์ จากคลองภาษีเจริญถึงคล...
Approved_buget                                               484500
Name: 72, dtype: object
------------------------
Item_name         ขุดลอกคลองสวนเลียบ จากคลองภาษีเจริญถึงจุดที่กำ...
Approved_buget                                               452900
Name: 73, dtype: object
------------------------
Item_name         ขุดลอกคลองสวนหลวงเหนือ จากคลองสวนอ้อยถึงคลองบา...
Approved_buget                                               440900
Name: 74, dtype: object
------------------------
Item_name         ขุดลอกคู คลอง ฯ
Approved_buget             331000
Name: 75, dtype: object
------------------------
Item_name         ขุดลอกลำรางแยกคลองบางขวด ตอน 1 \nจากคลองบางขวด...
Approved_buget                                              1044000
Name: 76, dtype: object
------------------------
Item_name         ขุดลอกลำรางแยกคลองบึงกุ่ม จากลำบึงกุ่ม\nถึงคลอ...
Approved_buget                                              1298000
Name: 77, dtype: object
------------------------
Item_name         ขุดลอกลำรางแยกคลองตาหนัง จากซอยนวมินทร์\n111 แ...
Approved_buget                                              2231000
Name: 78, dtype: object
------------------------
Item_name         ขุดลอกคลองยายเฮ้อ
Approved_buget                738000
Name: 79, dtype: object
------------------------
Item_name         ขุดลอกลำรางแยกคลองลำเจียก จากคลองลำเจียก\nถึงห...
Approved_buget                                               488000
Name: 80, dtype: object
------------------------
Item_name         ขุดลอกคลองพิณพาทย์ (จากถนนสมเด็จ\nพระปิ่นเกล้า...
Approved_buget                                                70000
Name: 81, dtype: object
------------------------
Item_name         ขุดลอกคลองสวนพริก (จากคลองบางพลัดถึงจุดที่กำหน...
Approved_buget                                               423000
Name: 82, dtype: object
------------------------
Item_name         ขุดลอกคลองตาเปล่ง จากคลองวัดกกถึงถนนพระรามที่ 2
Approved_buget                                              666000
Name: 83, dtype: object
------------------------
Item_name         ขุดลอกคลองแยกคลองเจ้าคุณจากคลองเจ้าคุณถึงคลองล...
Approved_buget                                              1141000
Name: 84, dtype: object
------------------------
Item_name         ขุดลอกคลองตรง จากคลองขวางบางปะแก้ว ถึงคลองขวาง...
Approved_buget                                              1216000
Name: 85, dtype: object
------------------------
Item_name         ขุดลอกคลองแยกคลองลัดเช็ดหน้า จากคลองลัดเช็ดหน้...
Approved_buget                                               434000
Name: 86, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองข้างวัดกก 2...
Approved_buget                                               416000
Name: 87, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงสาธารณประโยชน์หน้าวัดโพธิ์ทอง จา...
Approved_buget                                               412000
Name: 88, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร1 จาก...
Approved_buget                                               214000
Name: 89, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร 2 จา...
Approved_buget                                               138000
Name: 90, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงข้างโรงเรียนราชวินิตประถมบางแคจา...
Approved_buget                                              1045000
Name: 91, dtype: object
------------------------
Item_name         ขุดลอกคลองบางจากล่าง จากคลองบางขี้แก้ง \nถึงคล...
Approved_buget                                              1016000
Name: 92, dtype: object
------------------------
Item_name         ขุดลอกคลองยายพรุ้น (ฝั่งใต้) จากถนนบางแวก\nถึง...
Approved_buget                                              1468000
Name: 93, dtype: object
------------------------
Item_name         ขุดลอกลำกระโดงในชุมชนซอยสองคุณจ่า จากคลองภาษีเ...
Approved_buget                                              2202000
Name: 94, dtype: object
------------------------
Item_name         ขุดลอกคลองลัดครูเสงี่ยม จากคลองบางแวก ถึงคลองบ...
Approved_buget                                              1253000
Name: 95, dtype: object
------------------------
Item_name         ขุดลอกคลองผู้ใหญ่เส็ง 2 จากลำกระโดงเชื่อมคลองผ...
Approved_buget                                              1127000
Name: 96, dtype: object
------------------------
Item_name         ขุดลอกคลองโรงสี จากคลองภาษีเจริญถึงคลองบางอ้าย
Approved_buget                                           1137000
Name: 97, dtype: object
------------------------
Item_name         ขุดลอกคลองหนองยาว
Approved_buget              4706000
Name: 98, dtype: object
------------------------
Item_name         ขุดลอกคลองหนองตะแคง
Approved_buget                2401000
Name: 99, dtype: object
------------------------
Item_name         ขุดลอกคลองสามง่าม
Approved_buget               980000
Name: 100, dtype: object
------------------------
Item_name         ขุดลอกคลองตาเร่งจากถนนรามอินทรา\nถึงแยกคลองจรเ...
Approved_buget                                              1329000
Name: 101, dtype: object
------------------------
Item_name         ขุดลอกคลองบ้านเกาะจากถนนรามอินทรา\nถึงลำบึงกุ่...
Approved_buget                                              2118000
Name: 102, dtype: object
------------------------
Item_name         ขุดลอกคลองลำนุ่นจากลำบึงกุ่มถึงถนนรามอินทรา\n\n
Approved_buget                                            1913000
Name: 103, dtype: object
------------------------
Item_name         ขุดลอกลำรางสาธารณะ จากคลองทับช้างล่าง\nถึงถนนร...
Approved_buget                                               141000
Name: 104, dtype: object
------------------------
Item_name         ขุดลอกลำรางตาโห้ จากคลองแม่จัน\nถึงจุดที่กำหนด
Approved_buget                                            171000
Name: 105, dtype: object
------------------------
Item_name         ขุดลอกคลองลัดนิ่มไสว จากคลองบางพรหม\nถึงคลองบา...
Approved_buget                                               179000
Name: 106, dtype: object
------------------------
Item_name         ขุดลอกคลองผู้ใหญ่ จากคลองบางเชือกหนัง\nถึงคลอง...
Approved_buget                                               485000
Name: 107, dtype: object
------------------------
Item_name         ขุดลอกคลองแยกคลองบางไผ่ จากคลองบางไผ่\nถึงหมู่...
Approved_buget                                               134000
Name: 108, dtype: object
------------------------
Item_name         ขุดลอกคลองลำชะล่าจากคลองตาเร่ง\nถึงซอยรามอินทร...
Approved_buget                                              2600000
Name: 109, dtype: object
------------------------
Item_name         ขุดลอกคลองชักพระจากคลองบางกอกน้อย\nถึงคลองมอญ
Approved_buget                                          4581000
Name: 110, dtype: object
------------------------
Item_name         ขุดลอกคลองวัดเจ้าอามจากคลองชักพระ\nถึงถนนบางขุ...
Approved_buget                                              1015000
Name: 111, dtype: object
------------------------
Item_name         ขุดลอกคลองช่องนนทรีจากถนนสุรวงศ์\nถึงสถานีสูบน...
Approved_buget                                              9867000
Name: 112, dtype: object
------------------------
Item_name         ขุดลอกคลองจิตรมิตรมหาดไทย \nจากสถานีสูบน้ำคลอง...
Approved_buget                                              3218000
Name: 113, dtype: object
------------------------

In [ ]:
for row in data1.iterrows():
    #print(row)
    print(row[1]['Fiscal_year'])
    print('--------------------')

62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
62
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
63
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
64
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
65
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------
66
--------------------

# การสร้าง columns เพิ่ม

```df['ชื่อ column ใหม่'] = list of data # list of dataมีจน.สมาชิก = จน.row ของตาราง```

In [ ]:
small_df['ผู้รับผิดชอบ'] = ['ลุงตู่','ลุงตู่','ลุงป้อม','ชัชชาติ','พิธา']

<ipython-input-16-b13b24abd75e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_df['ผู้รับผิดชอบ'] = ['ลุงตู่','ลุงตู่','ลุงป้อม','ชัชชาติ','พิธา']

687     ลุงตู่
688     ลุงตู่
689    ลุงป้อม
690    ชัชชาติ
691       พิธา
Name: ผู้รับผิดชอบ, dtype: object

In [ ]:
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget,ผู้รับผิดชอบ
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000,ลุงตู่
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000,ลุงตู่
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000,ลุงป้อม
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000,ชัชชาติ
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000,พิธา

# การลบ columns

In [ ]:
small_df.drop(axis=1,columns=['Core_budget_code']) # axis คือ บอกว่าสนในเเกนไหน // จะdrop'Core_budget_code'ออก]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Expenditure_category,Item_name,Approved_buget,ผู้รับผิดชอบ
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000,ลุงตู่
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000,ลุงตู่
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางซาฟารี,689000,ลุงป้อม
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000,ชัชชาติ
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000,พิธา

In [ ]:
new_column = list ()
for row in data1.iterrows():
    new_col = f"{row[1]['Department']}-{row[1]['Expenditure_category']}-{row[1]['Item_name']}"
    new_column.append(new_col)

In [ ]:
data1 ['description'] = new_column
data1=data1.drop(axis=1,columns=['Department','Expenditure_category','Item_name'])

In [ ]:
data1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Core_budget_code,Approved_buget,description
0,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,1193000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองบางกะปิจากค...
1,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,1100000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองทรงกระเทียม...
2,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,3075000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองเป้งจากคลอง...
3,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,6240000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองลำพังพวยจาก...
4,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,2685000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกบึงรางเข้จากคลอ...
...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,NaN,3686000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกคลองผักกะเฉด
688,งบเพิ่มเติม,1,66,50460000,NaN,2575000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกคลองบึงทราย...
689,งบเพิ่มเติม,1,66,50460000,NaN,689000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกลำรางซาฟารี
690,งบเพิ่มเติม,1,66,50460000,NaN,464000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกลำรางตาจันทร์
691,งบเพิ่มเติม,1,66,50500000,NaN,7578000,สำนักงานเขตบางบอน-งบลงทุน-ขุดลอกคลองบางบอนต่อจ...

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[12653 rows x 3 columns]

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    # print(each_row[1]['sex'])
    if (each_row[1]['age'] <= 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(1466, sex                      ชาย
age                       19
province_of_onset    ขอนแก่น
Name: 1466, dtype: object)
(9333, sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 9333, dtype: object)
(9334, sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object)
(10610, sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 10610, dtype: object)
(11517, sex                      ชาย
age                       12
province_of_onset    ขอนแก่น
Name: 11517, dtype: object)
(11697, sex                     หญิง
age                       17
province_of_onset    ขอนแก่น
Name: 11697, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] <= 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

1466
sex                      ชาย
age                       19
province_of_onset    ขอนแก่น
Name: 1466, dtype: object
9333
sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 9333, dtype: object
9334
sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object
10610
sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 10610, dtype: object
11517
sex                      ชาย
age                       12
province_of_onset    ขอนแก่น
Name: 11517, dtype: object
11697
sex                     หญิง
age                       17
province_of_onset    ขอนแก่น
Name: 11697, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

       No.  ...                                               risk
6884  6885  ...                                  Cluster สมุทรสาคร
6885  6886  ...                                      Cluster ระยอง
6886  6887  ...                                        สถานบันเทิง
6887  6888  ...                                  Cluster สมุทรสาคร
6888  6889  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...

[5 rows x 10 columns]

In [ ]:
TF

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

### HW กลุ่ม 2 || เลือกข้อมูลมาเฉพาะวัน announce_date เป็นวันที่ 1-20

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.          age
count  12653.000000  8881.000000
mean    6327.000000    38.054748
std     3652.750813    15.125178
min        1.000000     0.100000
25%     3164.000000    27.000000
50%     6327.000000    36.000000
75%     9490.000000    48.000000
max    12653.000000    97.000000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

39.46076940331987

### ```.isnull()```

In [ ]:
data_covid.isnull()

         No.  announce_date  ...  district_of_onset   risk
0      False          False  ...               True  False
1      False          False  ...               True  False
2      False          False  ...              False  False
3      False          False  ...               True  False
4      False          False  ...               True  False
...      ...            ...  ...                ...    ...
12648  False          False  ...              False  False
12649  False          False  ...              False  False
12650  False          False  ...              False  False
12651  False          False  ...              False  False
12652  False          False  ...              False  False

[12653 rows x 10 columns]

# next

*   ต่อตารางแกน X แกน y
*   .groupby
*   save table